services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: redis
    volumes:
      - /data/nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载 Nginx 配置文件
    ports:
      - "443:443"
      - "80:80"
    
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    environment:
      REDIS_PASSWORD: 123456
    command: redis-server --requirepass 123456
    volumes:
      - /data/docker-data/redis:/data

  mariadb:
    image: mariadb:10.6.14
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    command: --lower-case-table-names=1
    volumes:
      - /data/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化 SQL 文件
      - /data/docker-data/mariadb:/var/lib/mysql

  video_message:
    image: webtao/scratch:zoneinfo
    container_name: video_message
    environment:
      DATABASE_URL: mysql://video:123456@mariadb:3306/video?timezone=Asia/Shanghai
      APP_API_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      APP_IMG_SERVER: https://img.xxxxxxxxxxxxxxx.cn/img
      APP_API_TIMEOUT: 600
      APP_MESSAGE_SIZE: 50
    volumes:
      - /data/apps/app:/app:ro
      - /data/his_path:/data/his_path:rw
      - /data/last_path:/data/last_path:rw