services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    volumes:
      - /data/video_root/nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载 Nginx 配置文件
    ports:
      - "443:443"
      - "80:80"

  video_message:
    image: webtao/scratch:zoneinfo
    container_name: video_message
    environment:
      APP_API_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  #PUSH_PLUS密钥
      APP_API_TOPIC: video                            #PUSH_PLUS群组编码
      APP_IMG_SERVER: https://img.xxxxxxxxxxxxxxx.cn/img #收到消息后，消息内图片的url地址前缀
      APP_API_TIMEOUT: 600
      APP_MESSAGE_SIZE: 50
    volumes:
      - /data/video_root/apps/app:/app:ro #应用可执行文件
      - /data/video_root/his_path:/data/his_path:rw  #存放历史截图
      - /data/video_root/last_path:/data/last_path:rw #存放最新的截图