name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
env:
  TARGET: x86_64-unknown-linux-musl
  ARTIFACT_NAME: videoMsg
  ARTIFACT_PATH: target/${{ env.TARGET }}/release/${{ env.ARTIFACT_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # 设置 GITHUB_TOKEN 权限
      contents: write  # 允许读取和写入内容，用于创建和更新 Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 更新至 v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        target: ${{ env.TARGET }}
        override: true

    - name: Install musl tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools musl-dev

    - name: Update CA certificates
      run: sudo update-ca-certificates

    - name: Build release
      run: cargo build --target x86_64-unknown-linux-musl --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 更新至 v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
    
    - name: Release
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: |
          ${{ env.ARTIFACT_PATH }}
        tag_name: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}  
        body: "Automated release for version ${{ github.ref_name }}"
        draft: false
        prerelease: false